[package]
name = "sairplay-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
num-bigint = "0.4.6"
rand = "0.8.5"
sha2 = "0.10.9"
hkdf = "0.12.4"
chacha20poly1305 = "0.10.1"
mdns-sd = "0.21.3"
plist = "=1.10.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
  "Win32_Foundation",
  "Win32_Media_Audio",
  "Win32_System_Com",
] }
